const express=require('express'),session=require('express-session'),helmet=require('helmet'),rateLimit=require('express-rate-limit'),bcrypt=require('bcryptjs'),multer=require('multer'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const app=express(),PORT=process.env.PORT||3000,DATA=path.resolve(process.env.DATA_DIR||path.join(__dirname,'data')),UP=path.join(DATA,'uploads'),DB=path.join(DATA,'resources.json'),AUTH=path.join(DATA,'admin-auth.json');
fs.mkdirSync(UP,{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,'[]');
const read=(p,d)=>{try{return JSON.parse(fs.readFileSync(p,'utf8'))}catch{return d}},write=(p,d)=>fs.writeFileSync(p,JSON.stringify(d,null,2)),safe=r=>({id:r.id,title:r.title,description:r.description,category:r.category,originalName:r.originalName,fileUrl:r.fileUrl,mimeType:r.mimeType,size:r.size,createdAt:r.createdAt});
app.disable('x-powered-by');app.set('trust proxy',1);app.use(helmet({contentSecurityPolicy:false}));app.use(express.json({limit:'1mb'}));app.use(express.urlencoded({extended:true}));
let secret=process.env.SESSION_SECRET; if(!secret){const p=path.join(DATA,'.session-secret');if(!fs.existsSync(p))fs.writeFileSync(p,crypto.randomBytes(48).toString('hex'),{mode:0o600});secret=fs.readFileSync(p,'utf8')}
app.use(session({name:'rw_resources_admin',secret,resave:false,saveUninitialized:false,cookie:{httpOnly:true,sameSite:'strict',secure:process.env.NODE_ENV==='production',maxAge:28800000}}));
app.use('/api/auth',rateLimit({windowMs:900000,limit:12}));app.use('/api/admin',rateLimit({windowMs:900000,limit:60}));app.use(express.static(__dirname));app.use('/uploads',express.static(UP,{index:false}));
const admin=(q,s,n)=>q.session?.admin?n():s.status(401).json({error:'Please sign in as administrator.'});
const upload=multer({storage:multer.diskStorage({destination:(q,f,cb)=>cb(null,UP),filename:(q,f,cb)=>cb(null,crypto.randomUUID()+path.extname(f.originalname).toLowerCase())}),limits:{fileSize:25*1024*1024},fileFilter:(q,f,cb)=>{const ok=/\.(pdf|png|jpe?g|gif|webp|svg|docx|pptx|zip|txt|csv|mp3|wav|ogg|mp4|webm)$/i.test(f.originalname);cb(ok?null:new Error('File type not allowed.'),ok)}});
app.get('/api/auth/status',(q,s)=>s.json({setupRequired:!read(AUTH,null),authenticated:!!q.session?.admin}));
app.post('/api/auth/setup',async(q,s)=>{if(read(AUTH,null))return s.status(409).json({error:'Password already set. Sign in instead.'});const p=String(q.body.password||'');if(p.length<12)return s.status(400).json({error:'Use at least 12 characters.'});try{fs.writeFileSync(AUTH,JSON.stringify({passwordHash:await bcrypt.hash(p,12),createdAt:new Date().toISOString()}),{flag:'wx',mode:0o600})}catch{return s.status(409).json({error:'Password already set. Sign in instead.'})}q.session.regenerate(e=>{if(e)return s.status(500).json({error:'Session error.'});q.session.admin=true;q.session.save(x=>x?s.status(500).json({error:'Session error.'}):s.json({ok:true}))})});
app.post('/api/auth/login',async(q,s)=>{const a=read(AUTH,null);if(!a)return s.status(428).json({error:'Set up a password first.'});if(!await bcrypt.compare(String(q.body.password||''),a.passwordHash))return s.status(401).json({error:'Incorrect password.'});q.session.regenerate(e=>{if(e)return s.status(500).json({error:'Session error.'});q.session.admin=true;q.session.save(x=>x?s.status(500).json({error:'Session error.'}):s.json({ok:true}))})});
app.post('/api/auth/logout',(q,s)=>q.session.destroy(()=>{s.clearCookie('rw_resources_admin');s.json({ok:true})}));
app.get('/api/resources',(q,s)=>s.json(read(DB,[]).map(safe).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.get('/api/admin/resources',admin,(q,s)=>s.json(read(DB,[]).map(safe).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))));
app.post('/api/admin/resources',admin,upload.single('file'),(q,s)=>{if(!q.file)return s.status(400).json({error:'Choose a file.'});const title=String(q.body.title||'').trim().slice(0,120);if(!title){fs.rm(q.file.path,()=>{});return s.status(400).json({error:'Title required.'})}const r={id:crypto.randomUUID(),title,description:String(q.body.description||'').trim().slice(0,1000),category:String(q.body.category||'General').slice(0,60),originalName:path.basename(q.file.originalname).slice(0,200),fileUrl:'/uploads/'+q.file.filename,mimeType:q.file.mimetype,size:q.file.size,createdAt:new Date().toISOString()};const all=read(DB,[]);all.push(r);write(DB,all);s.status(201).json({resource:safe(r)})});
app.delete('/api/admin/resources/:id',admin,(q,s)=>{const a=read(DB,[]),r=a.find(x=>x.id===q.params.id);if(!r)return s.status(404).json({error:'Not found'});write(DB,a.filter(x=>x.id!==r.id));fs.rm(path.join(UP,path.basename(r.fileUrl)),{force:true},()=>{});s.json({ok:true})});
app.get('/health',(q,s)=>s.json({ok:true}));app.use((e,q,s,n)=>s.status(400).json({error:e.message||'Request failed'}));app.listen(PORT,'0.0.0.0',()=>console.log('Resources site on '+PORT));